spring:
  config:
    import: optional:secrets.yml
  application:
    name: stock-api
  datasource:
    url: jdbc:mysql://localhost:3306/Stocks_System?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

